// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeAf66ZN_m24yEL6OuJ4lwZBao6P5e1YA',
    appId: '1:57671929777:web:088c738ed9b4073c22b790',
    messagingSenderId: '57671929777',
    projectId: 'fluttertask-e07ff',
    authDomain: 'fluttertask-e07ff.firebaseapp.com',
    storageBucket: 'fluttertask-e07ff.appspot.com',
    measurementId: 'G-C7TEQX6FWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJQFBvPrHLQnGfeTm_PPaVMlLr0knscL8',
    appId: '1:57671929777:android:9067411ef697549822b790',
    messagingSenderId: '57671929777',
    projectId: 'fluttertask-e07ff',
    storageBucket: 'fluttertask-e07ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCBSJnTYW6N9TG7q-VCEy6XTO5R8l8N04',
    appId: '1:57671929777:ios:1e28f6de52f1284522b790',
    messagingSenderId: '57671929777',
    projectId: 'fluttertask-e07ff',
    storageBucket: 'fluttertask-e07ff.appspot.com',
    iosBundleId: 'com.example.dashboard2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCBSJnTYW6N9TG7q-VCEy6XTO5R8l8N04',
    appId: '1:57671929777:ios:1e28f6de52f1284522b790',
    messagingSenderId: '57671929777',
    projectId: 'fluttertask-e07ff',
    storageBucket: 'fluttertask-e07ff.appspot.com',
    iosBundleId: 'com.example.dashboard2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeAf66ZN_m24yEL6OuJ4lwZBao6P5e1YA',
    appId: '1:57671929777:web:780ba8c491540c5d22b790',
    messagingSenderId: '57671929777',
    projectId: 'fluttertask-e07ff',
    authDomain: 'fluttertask-e07ff.firebaseapp.com',
    storageBucket: 'fluttertask-e07ff.appspot.com',
    measurementId: 'G-SSYBT9C87X',
  );
}
